### ISSUE TITLE
symbolic links zipped in the replica pre-processed files

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#1]
Hello,

First I would like to thank you for your great work, 

When I unzipped the replica preprocessed file you shared in [OneDrive](https://umass-my.sharepoint.com/:u:/g/personal/tdngo_umass_edu/ERkM9wSgo1BJoZqNOwBuhlABgw42v5P5oiZCChjA3ZQ1og?e=bIYEKx) I found that the two files "cls_agnostic_replica_scannet200" and "dc_feat_replica_scannet200" are symbolic links to other files (which can't be opened), could you please share the original ones?

These are some details on the zipped files:

finishing deferred symbolic links:
  cls_agnostic_replica_scannet200 -> /home/tdngo/Workspace/3dis_ws/ISBNet/results/cls_agnostic_replica_scannet200
  dc_feat_replica_scannet200 -> /home/tdngo/Workspace/3dis_ws/ISBNet/results/dc_feat_replica_scannet200

Many thanks,
Mohamed

**Comment by ngoductuanlhp** [comment]
We've updated the link for the Replica dataset. Thanks for letting us know.

Best.
