### ISSUE TITLE
Installing libsparsehash-dev 

### ISSUE THREAD

**Issue by Bozcomlekci** [VinAIResearch/Open3DIS#11]
Greetings,

I don't have sudo permissions in the system that I'm trying to install the repository to

Do you know an alternative to `sudo apt-get install libsparsehash-dev`? I have already tried `conda install google-sparsehash -c bioconda`  and  `conda install -y conda-forge::sparsehash` but they don't seem to work as I am still getting:

`fatal error: google/dense_hash_map: No such file or directory`

**Comment by PhucNDA** [comment]
Hi @Bozcomlekci, 
Have you tried : `apt-get install -y libsparsehash-dev` ?

**Comment by PhucNDA** [comment]
Hello @Bozcomlekci,

Before installing libs, make sure to run `apt-get update.`
As for the Python path for specific modules, execute the bash script I provided (where I exported the correct PYTHONPATH), and that should resolve the issue.
