### ISSUE TITLE
ValueError while installing GoundingDINO

### ISSUE THREAD

**Issue by trayOWO** [VinAIResearch/Open3DIS#12]
When installing groundingDINO model in conda environment, we got a value error as below:

> Installing collected packages: addict, scipy, safetensors, regex, opencv-python-headless, opencv-python, fsspec, filelock, defusedxml, yapf, huggingface_hub, tokenizers, timm, supervision, transformers, groundingdino
>   Running setup.py develop for groundingdino
>     error: subprocess-exited-with-error
> 
>     × python setup.py develop did not run successfully.
>     │ exit code: 1
>     ╰─> [78 lines of output]
>         fatal: not a git repository (or any of the parent directories): .git
>         Building wheel groundingdino-0.1.0
>         Compiling without CUDA
>         running develop
>         running egg_info
>         writing groundingdino.egg-info\PKG-INFO
>         writing dependency_links to groundingdino.egg-info\dependency_links.txt
>         writing requirements to groundingdino.egg-info\requires.txt
>         writing top-level names to groundingdino.egg-info\top_level.txt
>         reading manifest file 'groundingdino.egg-info\SOURCES.txt'
>         C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
>         !!
> 
>                 ********************************************************************************
>                 Please avoid running ``setup.py`` and ``easy_install``.
>                 Instead, use pypa/build, pypa/installer or other
>                 standards-based tools.
> 
>                 See https://github.com/pypa/setuptools/issues/917 for details.
>                 ********************************************************************************
> 
>         !!
>           easy_install.initialize_options(self)
>         C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
>         !!
> 
>                 ********************************************************************************
>                 Please avoid running ``setup.py`` directly.
>                 Instead, use pypa/build, pypa/installer or other
>                 standards-based tools.
> 
>                 See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>                 ********************************************************************************
> 
>         !!
>           self.initialize_options()
>         Traceback (most recent call last):
>           File "<string>", line 2, in <module>
>           File "<pip-setuptools-caller>", line 34, in <module>
>           File "C:\Users\USER\Desktop\nthu\3-2\pui\Open3DIS-main\segmenter2d\GroundingDINO\setup.py", line 200, in <module>
>             setup(
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\__init__.py", line 103, in setup
>             return distutils.core.setup(**attrs)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>             return run_commands(dist)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>             dist.run_commands()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>             self.run_command(cmd)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\dist.py", line 989, in run_command
>             super().run_command(command)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>             cmd_obj.run()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\develop.py", line 34, in run
>             self.install_for_development()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\develop.py", line 105, in install_for_development
>             self.run_command('egg_info')
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>             self.distribution.run_command(command)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\dist.py", line 989, in run_command
>             super().run_command(command)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>             cmd_obj.run()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\egg_info.py", line 318, in run
>             self.find_sources()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
>             mm.run()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\egg_info.py", line 548, in run
>             self.add_defaults()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\egg_info.py", line 593, in add_defaults
>             self.read_manifest()
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\sdist.py", line 214, in read_manifest
>             self.filelist.append(line)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\command\egg_info.py", line 485, in append
>             path = convert_path(item)
>           File "C:\Users\USER\anaconda3\envs\Open3DIS\lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
>             raise ValueError("path '%s' cannot be absolute" % pathname)
>         ValueError: path '/root/CVPR24/Open3DIS/segmenter2d/GroundingDINO/groundingdino/models/GroundingDINO/csrc/cuda_version.cu' cannot be absolute
>         [end of output]
> 
>     note: This error originates from a subprocess, and is likely not a problem with pip.

We don't have any idea about where the path "/root/CVPR2024..." come from, and should we modify the path to resolve the issue?
Thank you very much!! OWQ

**Comment by ngoductuanlhp** [comment]
The issue is likely due to an incorrect CUDA installation. Please refer to the original repository of GroundingDINO at [this link](https://github.com/IDEA-Research/GroundingDINO).
