### ISSUE TITLE
GroundedDINO version

### ISSUE THREAD

**Issue by Yebulabula** [VinAIResearch/Open3DIS#13]
Hi author,

In your paper, you claim that "For Grounded-SAM, we utilize the Swin-B Grounding DINO decoder". However, I found that you actually utilize the Swin-T Grounding DINO decoder. May I ask if we could safely lift the decoder to Swin-B. Thanks.

Best wishes,
Ye Mao

**Comment by PhucNDA** [comment]
Hi @Yebulabula,
Sorry for the mistake in the paper. I think it is safe to use Swin-B Grounding DINO decoder with the current source code. You can check the generated box || masks by turning this on:
https://github.com/VinAIResearch/Open3DIS/blob/main/tools/grounding_2d.py#L300

Best.
