### ISSUE TITLE
Failed to get the superpoint of Replica

### ISSUE THREAD

**Issue by intro965** [VinAIResearch/Open3DIS#14]
I'm getting an error when I try to get the superpoint of Replica. Have you encountered this problem?
![image](https://github.com/VinAIResearch/Open3DIS/assets/58054754/b24c0c9d-d791-4238-a358-09f5ee7dc0d9)

**Comment by PhucNDA** [comment]
Hi @intro965,
We provide the processed Replica dataset [here](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md).

Best.

**Comment by intro965** [comment]
This data sample half of the original points. How to get superpoint result for original points?

**Comment by shjung13** [comment]
I also faced this issue. The provided Replica dataset has only half of the points. 

However, the original dataset has polygon mesh so superpoint algorithm cannot be applied.

So, I used Meshlab to convert it to triangle mesh while maintaining the number of points.
(Filters > Remeshing, Simplification and Reconstruction > Turn into a Pure-Triangular mesh)

Hope this works in your case.

**Comment by ngoductuanlhp** [comment]
Hi,

For processing the original mesh files from the Replica dataset, we use `trimesh`, which automatically converts polygon meshes to triangular meshes and run the superpoint segmentation from ScanNet. We then sample and retain only half of the points to save storage.

Best.

**Comment by jeff2048** [comment]
Hi, could you please provide how you get the split files? Thank you.
