### ISSUE TITLE
Inconsistent number of frames in the given validation scannet200 scene and rendered scene.

### ISSUE THREAD

**Issue by Yebulabula** [VinAIResearch/Open3DIS#15]
Dear author,

Sorry to bother you again. I am writing to seek clarification about the frame count in the validation ScanNet200 example, which totals 475 frames. Following the standard ScanNet rendering process in "https://github.com/ScanNet/ScanNet/tree/master/SensReader/python", I generated RGB-D images from a .sens file, but ended up with a significantly higher frame count. Could you explain the discrepancy?

Thank you for your assistance.

Best regards,
Ye Mao

**Comment by PhucNDA** [comment]
Hi @Yebulabula,
We capture RGB-D frames at intervals of 5, indicating that we record and append the results to the self.frames list every 5 invocations of this class constructor: [here](https://github.com/ScanNet/ScanNet/blob/master/SensReader/python/SensorData.py#L73)

Best.

**Comment by Yebulabula** [comment]
Thanks for your quick reply. It is really helpful. Another question is that when I perform promptable segmentation, what is the most effective method to filter unnecessary 3D proposals? I found Open3DIS normally generates a bunch of masks for a single text prompt, but we only need one finally. I tried to select the 3D proposal with the highest CLIP confidence as the final mask. But this confidence value is not always reliable. Do you have some advice on it? Thanks.

**Comment by Yebulabula** [comment]
Additionally, I am confused about when we conduct promptable segmentation, do we really need CLIP for further class label assignment? Why don't we merge multiple 2D masks into a single 3D proposal, and use it as the final segmentation result?

**Comment by PhucNDA** [comment]
Hi @Yebulabula,

**A1:**  For post-processing techniques, you can explore various NMS algorithms at [ISBNet](https://github.com/VinAIResearch/ISBNet/blob/master/isbnet/model/model_utils.py), filtering techniques at [OVIR-3D](https://github.com/shiyoung77/OVIR-3D/blob/main/src/proposed_fusion.py#L164C5-L164C34), DBScan at [Segment3D](https://arxiv.org/pdf/2312.17232) and many other heuristic algorithms...

**A2:**  Certainly, you can utilize the lifted 2D masks from 2Dsegmenter as the final result for promptable segmentation. However, 2D masks derived from 2Dsegmenter are typically noisy (as can be seen by enabling [this script](https://github.com/VinAIResearch/Open3DIS/blob/main/tools/text_query.py#L365)), which might lead to unreliable results. For instance, when querying "Hoverboard" in a 3D scene, certain views may show the 2Dsegmenter incorrectly segmenting a chair, resulting in an inaccurate final result (in green version). Conversely, our method incrementally refines CLIP features to filter out false predictions, as demonstrated in the red version. This approach, using CLIP features, is developed by our [VinAI-3DIS team OpenSUN3D](https://arxiv.org/pdf/2312.17232)

![image](https://github.com/VinAIResearch/Open3DIS/assets/108280892/10e351ce-4572-4048-b385-4398b1700b6c)
![image](https://github.com/VinAIResearch/Open3DIS/assets/108280892/5781c2c0-11d1-4270-8686-b1025c7aaf4e)
![image](https://github.com/VinAIResearch/Open3DIS/assets/108280892/977b6b7f-ff4b-42e6-9141-bb04331cbce7)
If you have any question, feel free to let me know.

Best.

**Comment by PhucNDA** [comment]
If you have any question, feel free to re-open the issue
