### ISSUE TITLE
Generating class-agnostic 3D proposals and 3D deep features using ISBNet

### ISSUE THREAD

**Issue by dihydrogen-monocide** [VinAIResearch/Open3DIS#18]
Dear authors,

I have a problem while trying to generate **class-agnostic 3D proposals** and **3D deep features** using ISBNet.
I followed the data preparation instructions, and I tried running the demo as instructed in `DATA.md`, which was:
```python
# Download the pre-trained ISBNet on Scannet200 or V2 to acquire deep level feature
cd segmenter3d/ISBNet/
python3 tools/test.py configs/scannet200/isbnet_scannet200.yaml pretrains/scannet200/head_scannetv2_200_val.pth
``` 
However, after running, it only printed out the results, and I wasn't able to find the `.pth` files of the class-agnostic 3D proposals and 3D deep features. I tried enabling the `--out` argument:
```python
python3 tools/test.py configs/scannet200/isbnet_scannet200.yaml pretrains/scannet200/head_scannetv2_200_val.pth --out OUTPUT/PATH
``` 
but it only exports the predictions for the ScanNetV2 hidden benchmark in `.txt` files.

Did I miss any settings or configurations? Could you provide instructions to generate the class-agnostic 3D proposals and 3D deep features `.pth` files using the pre-trained ISBNet, please?

Thank you!

**Comment by PhucNDA** [comment]
Hi @dihydrogen-monocide,
Make sure that the class-agnostic 3D proposals directory and 3D deep features directory exist before running ISBNet. We will update the source code. Thanks for letting us know.

Best.

**Comment by dihydrogen-monocide** [comment]
Hi @PhucNDA ,
Thanks a lot for your response.

However, I'm still confused a little bit about where exactly should I put those directories, and what should I do with them:
1. Should I just create empty folders for the class-agnostic 3D proposals and 3D deep features so that when I run the `tools/test.py` it will save the results in those folders later or what else? And where should I create those folders?
2. Should I specify anything while running the `tools/test.py`, because when I checked the code, I wasn't able to find the code in charge of saving class-agnostic 3D proposals and 3D deep features, or did I miss it? If so, please let me know where it was.

Thank you!

**Comment by PhucNDA** [comment]
Hi @dihydrogen-monocide,

Regarding the saving path, you can check below:
We save the feature [here](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/isbnet/model/isbnet.py#L482). Class-agnostic proposals [here](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/isbnet/model/isbnet.py#L635)

Best.

**Comment by dihydrogen-monocide** [comment]
Hi @PhucNDA,

Thank you for the clarification, I greatly appreciate your help.

Best.

**Comment by jeff2048** [comment]
> Hi @dihydrogen-monocide,
> 
> Regarding the saving path, you can check below: We save the feature [here](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/isbnet/model/isbnet.py#L482). Class-agnostic proposals [here](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/isbnet/model/isbnet.py#L635)
> 
> Best.

Hi, it seems that this only works for scannet200 scannetpp and arkitscenes. What about s3dis and replica?
