### ISSUE TITLE
Regarding OVIR-3D results in your paper

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#19]
Dear authors,

Thanks again for your amazing work,

I just wanted to ask you about the results for OVIR-3D you are reporting in your paper.

In their paper, they are sharing the following:
mAP25:56.4 mAP50:44.3 mAP:21.1 

While in your paper you are reporting: 
mAP25:32.3 mAP50:24.9 mAP:13.0

It would be great if you could share some details about the reason behind this difference, was it because of using a different evaluation script, because I noticed that they are using [this one](https://github.com/rafaelpadilla/Object-Detection-Metrics/blob/master/lib/Evaluator.py) instead of scannet200 script

Many thanks,
Mohamed

**Comment by ngoductuanlhp** [comment]
Hi, the evaluation process from OVIR-3D is actually not the instance segmentation evaluation. You can see the reply from its authors https://github.com/shiyoung77/OVIR-3D/issues/4#issuecomment-1785208360

**Comment by aminebdj** [comment]
Hey @ngoductuanlhp,

Thanks a lot for the clarification.
