### ISSUE TITLE
Struggle with understanding when / how to run ISBNet and Superpoint

### ISSUE THREAD

**Issue by knsjoon** [VinAIResearch/Open3DIS#20]
Here are the steps that you have mentioned how to run the code. 

1) Extract 2D masks and first stage feature from RGB-D sequences

2) Generate 3D instances from 2D masks

3-A) Refine second stage feature from 3D instances

3-B) After refine grounded features, re-run step 2 to finalize the 3D output masks

4) Run interactive visualization (required Pyviz3D)

I have a question at what stage I need to run ISBNet and SuperPoint for the whole pipeline to run. I managed to run step 1 but I am not too sure if step 2 requires ISBNet result and SuperPoint result. 

Also, can I download the latest version of ISBNet and Superpoint? I am wondering as you have mentioned that for segment2d (SAM and GroundingDINO) to stick with the codes that were included in the github repo due to some changes you made, right?

I read your paper and it is a very cool! So I am striving to make the code run the whole pipeline with scannetpp and then with my own dataset afterwards.

**Comment by PhucNDA** [comment]
Hi @knsjoon,

Thank you for your interest in our work!

For the ScanNetpp 3D data, you can find the latest spp and the pre-computed isbnet_clsagnostic (pretrained200) [here](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md).

To generate 3D proposals using the 3D backbone, initiate the process which should compute the entire 50 validation scenes in about 1-2 minutes (you should run before step 3-A). If you wish to customize which stream of proposals to use for final predictions, you can adjust the settings in the configs [here](https://github.com/VinAIResearch/Open3DIS/blob/main/configs/scannetpp.yaml#L55).

Should you have any questions, please feel free to ask.

Best regards,
PhucNDA.

**Comment by PhucNDA** [comment]
Hi @knsjoon 

**Q1:** Yes. calling `grounding_2d.sh` generates 2D proposals and corresponding first stage pointclould feature.

**Q2:** You can follow the ScanNet repo with the [segmentator.cpp](https://github.com/ScanNet/ScanNet/blob/master/Segmentator/segmentator.cpp) to extract the superpoints from 3D point cloud reconstruction. About [k_threshold](https://github.com/ScanNet/ScanNet/blob/master/Segmentator/segmentator.cpp#L270), we use the default value as same as ScanNet200 (V2). You can adjust this parameter for your custom dataset.

**Q3:** The configuration file  of ISBNet is available [here](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/configs/scannetpp/isbnet_scannetpp.yaml). Before running `python tools/test.py`, make sure the these [directories ](https://github.com/VinAIResearch/Open3DIS/blob/main/segmenter3d/ISBNet/isbnet/model/isbnet.py#L646) existed.

**Q4:** Yes, the 'plus' sign is simple 3D proposal concatenation. Detailed [here](https://github.com/VinAIResearch/Open3DIS/blob/main/tools/generate_3d_inst.py#L125).

Best,
PhucNDA.
