### ISSUE TITLE
when running "sh scripts/generate_3d_inst.sh" 

### ISSUE THREAD

**Issue by Jasper-kk** [VinAIResearch/Open3DIS#23]
face 

sh scripts/generate_3d_inst.sh
  0%|                                                                              | 0/50 [00:00<?, ?it/s]Process 09c1414f1b
  0%|                                                                              | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/generate_3d_inst.py", line 278, in <module>
    cluster_dict = torch.load(os.path.join(save_dir_cluster, f"{scene_id}.pth"))
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/Open3DIS/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../exp_scannetpp/version_sam/hier_agglo/09c1414f1b.pth'

Thanks

**Comment by Jasper-kk** [comment]
and when I try this one "sh scripts/grounding_2d.sh configs/replica.yaml pretrains/foundation_models/groundingdino_swint_ogc.pth"
still have problem "OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'."

**Comment by PhucNDA** [comment]
Hi @Jasper-kk 
The repository has been updated recently with new features! 
Have you solved the problem?

Best,
PhucNDA.
