### ISSUE TITLE
About performance on Open3DIS and Segment Anything Model

### ISSUE THREAD

**Issue by shjung13** [VinAIResearch/Open3DIS#27]
Hello authors,

I deeply appreciate for the great work!

I was running the code on the ScanNetv2-200 dataset and found several questions I would like to ask!
1) In dataset configuration for ScanNet200, the paper says you used 10 as a downsampling factor for the number of images.
However, in the README file, it says you used 5 as a downsampling factor. Would you let me know which number is the correct one to use?

2) We found that you made several changes on ISBNet architecture. We wonder whether this changes is intended.
When I validate the performance on the validation set, I got around 0.2 mAP and 0.27 AP_{50} while its original performance with ISBNet official code is 0.24 and 0.32. (After reverting changes in isbnet.py file, I was able to achieve the same performance as ISBNet official repository)

3) When the script load Segment-Anything Model, it uses SAM-HQ. However, in the paper, it seems like the original SAM model is used and in the README file, the instructions say that we need to download SAM model.
Due to this mismatch, when we load the weight, it outputs Incompatible Keys and this could result in performance drop.

4) In general, I can't reproduce the numbers reported in the original paper using the current code. I am trying original SAM or SAM-HQ weights to reproduce the performance (seems this is critical).

Would you let me know if these questions are legit and right direction to debug the problem?

Thank you in advance!

Best,
Sanghun

Thank you.

**Comment by PhucNDA** [comment]
Hi @shjung13,

1. Note that we use the interval of 2 (looping every 5 x 2 frames). This can be illustrated in our sub-dataset released on Google Drive. You can check [here](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md). We pre-extract 5 frames each on ScanNet200 and ScanNet++ datasets.
2.  Thanks for letting us know, we are updating/refactoring the code based on ppl's feedback at CVPR'24 and will investigate the change in isbnet.py file.
3.  For the current version, we also use SAM-HQ for Segment Anything Model the same as in the paper reported.
4.  To reproduce the number in the paper, you should use SAM-HQ, CLIP ViT-L/14@336, Swin-T Grounding DINO. 

I might not know the problem you're facing, If possible, hope you could elaborate more about it! Feel free to ask me anything!

Best,
PhucNDA.

**Comment by shjung13** [comment]
Hi @PhucNDA 

Thank you so much for the quick response!

I put more information below to help you debug and understand the problem 2 and 3.

2) For reverting ISBNet changes, I only changed this line to False: https://github.com/VinAIResearch/Open3DIS/blob/132fb694b9498cee03bf86e4a70bcaa7b68bb97c/segmenter3d/ISBNet/isbnet/model/isbnet.py#L923

3) For SAM and SAM-HQ, the grounding_2d uses SAM-HQ for loading the weights but the config is using SAM weights.
Grounding_2d: https://github.com/VinAIResearch/Open3DIS/blob/132fb694b9498cee03bf86e4a70bcaa7b68bb97c/tools/grounding_2d.py#L155
Config: https://github.com/VinAIResearch/Open3DIS/blob/132fb694b9498cee03bf86e4a70bcaa7b68bb97c/configs/scannet200.yaml#L4

I hope this helps :)

Best,
Sanghun

**Comment by shjung13** [comment]
Would using `scripts/eval.sh` file for evaluation be the right way to reproduce your 2D+3D performance? It is reading `final_result_hier_agglo` directory.

**Comment by PhucNDA** [comment]
Hi @shjung13,
p2d and p3d decide whether you want the results to be included the 2D-lifted || 3D-ISBNet masks.
To achieve the best result, I suggest you turn both of these flags on.

Best,
PhucNDA.
