### ISSUE TITLE
Reproduce OpenYolo3D on Replica

### ISSUE THREAD

**Issue by soumajm** [VinAIResearch/Open3DIS#29]
Hi, 

thanks for your repo and also your code for the OpenYolo3D part.

I was running the scripts/reproduce_openyolo3d.sh and got an error from from the following [line](https://github.com/VinAIResearch/Open3DIS/blob/main/tools/reproduce_openyolo3d.py#L121)

```data_path = './data/Scannet200/Scannet200_3D/Scannet200_open3dis_ISBNet_DETIC'```

Should it be instead pointed to a directory from this [zip](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md#replical)?

**Comment by PhucNDA** [comment]
Hi @soumajm,

Sorry for the late reply, the folder is the set of 3D proposals with the same data format as this [line](https://github.com/VinAIResearch/Open3DIS/blob/main/tools/generate_3d_inst.py#L313).
The 2D proposals require the class name for OpenYOLO3D, so in this case, we can use RAM-YOLOWorld for open-ended class names from RAM [this line](https://github.com/VinAIResearch/Open3DIS/blob/main/util2d/ram_yoloworld_sam.py#L213) or YOLOWorld for open-vocab class names [this line](https://github.com/VinAIResearch/Open3DIS/blob/main/util2d/yoloworld_sam.py#L192). The code supports both open-ended 3DIS and open-vocab 3DIS.

Best,
PhucNDA.
