### ISSUE TITLE
[Question] I want to use Mask3D features instead if ISBNET for dc_features computation 

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#3]
Hello,

Thanks again for the work,

I used Mask3D features to compute the dc_features; I was wondering which ones you used for the results reported in the paper (with mask3d): the 128-dimensional (mask feature) or the 96-dimensional (Backbone Point cloud features)?

Many thanks,
Mohamed

**Comment by ngoductuanlhp** [comment]
Hi @aminebdj ,

We extracted feature after the mask_features_head in Mask3D ([here](https://github.com/JonasSchult/Mask3D/blob/11bd5ff94477ff7194e9a7c52e9fae54d73ac3b5/models/mask3d.py#L256)).

Best.

**Comment by aminebdj** [comment]
Hey @ngoductuanlhp,

Thanks for the clarification,

Best

**Comment by LiangXu123** [comment]
> Hey @ngoductuanlhp,
> 
> Thanks for the clarification,
> 
> Best

did you figure out how to extract Mask3D features? 

for example. how to save the dc_features and cls_agnostic_3d_proposals in Mask3D like ISBNet below:

        if self.dataset_name == "scannet200":
            save_path = os.path.join(self.dc_200, scan_ids[0] + ".pth")
            # torch.save((voxel_mask_features[v2p_map.long()].cpu()), save_path)
        if self.dataset_name == "scannetpp":
            save_path = os.path.join(self.dc_pp, scan_ids[0] + ".pth")
        torch.save((voxel_mask_features[v2p_map.long()].cpu()), save_path)

        if self.dataset_name == "scannet200":
            saved_masks = [m["pred_mask"] for m in pred_instances]
            saved_confs = [m["conf"] for m in pred_instances]
            torch.save(
                {"ins": saved_masks, "conf": saved_confs},
                os.path.join(self.isbnt_200, scan_ids[0] + ".pth"),
            )
        if self.dataset_name == "scannetpp":           
            saved_masks = [m["pred_mask"] for m in pred_instances]
            saved_confs = [m["conf"] for m in pred_instances]
            torch.save(
                {"ins": saved_masks, "conf": saved_confs},
                os.path.join(self.isbnt_pp, scan_ids[0] + ".pth"),
            )
