### ISSUE TITLE
when running sh scripts/grounding_2d.sh

### ISSUE THREAD

**Issue by jeff2048** [VinAIResearch/Open3DIS#32]
I got this issue:

Traceback (most recent call last):
  File "/home/zongyan/codes/open_voca/Open3DIS-main/tools/grounding_2d.py", line 79, in <module>
    with open("tracker_2d.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'tracker_2d.txt'

Could you please tell me how to get this file?

Best Regards

**Comment by PhucNDA** [comment]
Hi @jeff2048,

You can refer to issue #9 .

Best,
PhucNDA
