### ISSUE TITLE
Use on Custom dataset 

### ISSUE THREAD

**Issue by Inshu32** [VinAIResearch/Open3DIS#35]
Can the Open3DIS algorithm be used on custom dataset. I have a unique point cloud dataset from a construction site. I want to classify it according to some custom classes. 

Is there a way to use Open3DIS for it ?

**Comment by PhucNDA** [comment]
Hi @Inshu32,
After preparing your data as the [data_prepartation guide](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md), you can run the script [text_query](https://github.com/VinAIResearch/Open3DIS/blob/main/scripts/text_query.sh) for arbitrary language text query on your custom 3D point cloud scene.
