### ISSUE TITLE
Result of ScanNet 200 Instance Segmentation in the paper

### ISSUE THREAD

**Issue by Louis708** [VinAIResearch/Open3DIS#37]
Hello @PhucNDA,

I download the Result_OpenVocab_ISBNet-GSAM file and evaluate it on the ScanNet 200 dataset. I use the default script and just change the file path. I get the below results:

```
ScanNet200 Evaluation
################################################
what           :      AP  AP_50%  AP_25%
################################################
Head AP        :   0.257   0.316   0.343
Common AP      :   0.203   0.254   0.287
Tail AP        :   0.229   0.281   0.317
Base AP        :   0.250   0.314   0.351
Novel AP       :   0.222   0.272   0.302
------------------------------------------------
AP             :   0.230   0.284   0.316
################################################
```

It seems that the results of 0.230, 0.284, 0.316 is a bit different from the paper's 0.237, 0.294, 0.328. Is the gap within the acceptable range? Or do I miss some steps for evaluation?

**Comment by PhucNDA** [comment]
Hi @Louis708,

The Result_OpenVocab_ISBNet-GSAM folder you downloaded does not use a post-processing feature (I uploaded this temporary version for the sake of people's requirements at CVPR. So, I shortened some processes to make it quicker for people to access and test during the conference).
You can achieve the in paper's results by unlocking this post-processing feature: [here](https://github.com/VinAIResearch/Open3DIS/blob/main/open3dis/src/clustering/clustering.py#L895)

Should you have any concerns, feel free to ask me!
Best,
PhucNDA.
