### ISSUE TITLE
ScanNet++ results

### ISSUE THREAD

**Issue by tberriel** [VinAIResearch/Open3DIS#39]
Hi, 
first of all, congrats for your nice work!
I was wondering if you could share your class agnostic results on ScanNet++ validation set. They would be really useful :D

**Comment by PhucNDA** [comment]
Hello @tberriel,

We have included the class-agnostic performance on ScanNet200 and ScanNet++ on [link](https://open3dis.github.io/)

Best,
PhucNDA.

**Comment by tberriel** [comment]
Hi, @PhucNDA ,
I was talking about to the actual 3D representation. In the [Data Preparation ReadMe ](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md) you shared the links for the ScanNet200, but the link for ScanNet++ (Scannetpp_ClsAg_SAM) is missing.
Thanks!
