### ISSUE TITLE
Mapping the replica masks to the original scene dimension

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#5]
Hello,

It seems that the replica scenes provided are sampled from the original replica scenes. Is it possible to provide mapping to the original dimension if it exists, and also, some details on the pre-processing phase if possible?

Many thanks, 
Mohamed

**Comment by ngoductuanlhp** [comment]
Hi @aminebdj,

Here is the link to the raw Replica dataset and our preprocess script ([Onedrive](https://umass-my.sharepoint.com/:u:/g/personal/tdngo_umass_edu/EQbnqSqt9UBKtFkXBx0sKpsB31t4K-IKhPkI8Lj4nzqNkA?e=24DxLa)). We simply sample half of the original points. For the superpoint, we leverage [this repo](https://github.com/ScanNet/ScanNet/tree/master/Segmentator) or you could take a look at this recent work [SuperpointTransformer](https://github.com/drprojects/superpoint_transformer).

Best.
