### ISSUE TITLE
Promptable Segmentation

### ISSUE THREAD

**Issue by Yebulabula** [VinAIResearch/Open3DIS#7]
Dear authors,

Thanks for your fantastic work. 

I am curious about whether Open3DIS supports promptable segmentation (e.g., text-conditional segmentation) like traditional 2D SAM. Based on your visualization shown in your GitHub page, it seems Open3DIS can output a mask that accurately corresponds to the input text prompt. May I ask when will you add this function to this repository?

Best wishes,
Ye

**Comment by PhucNDA** [comment]
Hi @Yebulabula,

I have committed the promptable segmentation (Grounded SAM, 2D only) script for Open3DIS.
You can modify text query at [here](https://github.com/VinAIResearch/Open3DIS/blob/main/scripts/text_query.sh#L4) (For example, query 3 object categories: 'object1.object2.object3')

Below I use Grounded SAM for 'chair.table' prompt
![image](https://github.com/VinAIResearch/Open3DIS/assets/108280892/94d78e47-41ad-4596-8745-c876730cfc93)

If you have any concerns, please feel free to let me know.

Best.

**Comment by PhucNDA** [comment]
Hi @Yebulabula,

The current class-agnostic 3D segmenters of Open3DIS, such as ISBNet, Mask3D, SoftGroup, etc., do not currently support promptable segmentation. For investigating on detailed design of end-to-end grounding backbones, you can refer to the [ScanRefer](https://kaldir.vc.in.tum.de/scanrefer_benchmark/) benchmark.

Best.
