### ISSUE TITLE
running the generate_3d_inst :  No such file or directory: 'tracker_lifted.txt'

### ISSUE THREAD

**Issue by RongkunYang** [VinAIResearch/Open3DIS#9]
Hello, dear authors, thank you for your great work.
When I run the generate_3d_inst.sh for ScanNet200, the error exists:
Traceback (most recent call last):
  File "tools/generate_3d_inst.py", line 292, in <module>
    with open("tracker_lifted.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'tracker_lifted.txt'

So what does this file use for?

**Comment by PhucNDA** [comment]
Hi @RongkunYang,
The tracker files are used to keep track of processed scenes. You can simply uncomment this Line: https://github.com/VinAIResearch/Open3DIS/blob/main/tools/generate_3d_inst.py#L279
